print("WELCOME TO START-UP FILE")
print("------------------------")
import mysql.connector
con = mysql.connector.connect(host="localhost", user="root", passwd="yoursqlpassword")
mycursor = con.cursor()
def setup():
    print('')
    print('HELLO USER!')
    print('-----------')
    ch=int(input("(1)Rules\n(2)Setup\n(3)Help\n(4)Exit\nEnter:"))
    print('')
    if(ch==1):
        print('BASIC THINGS AND PROCEDURES FOR RUNNING THIS CODE')
        print('-------------------------------------------------')
        print('1)Before running the main file, you need to setup your program using choice(2) in this file\n2)Open the IDLE version of both the files and type in your "SQL Password"')
        print('3)After that, open the main program and in the "WELCOME TO LIBRARY" block, enter choice as "10"\n4)Now, you will be redirected to the SUPERVISOR block')
        print('5)In SUPERVISOR block, you need to log-in using your id and password and ADD STAFFS to run your library\n6)Now,go back to "WELCOME BLOCK", and go to "STAFFS" using the given ID and password')
        print('6)Being a Staff,"ADD BOOKS" to the library\n7)Now, you can go back to "WELCOME BLOCK", and then to "STUDENTS", and login as a "NEW STUDENT" and take your wanted books, after viewing them using "VIEW BOOKS"')
        print('')
        print('NOTE: THE ABOVE STEPS ARE FOR THE FIRST-TIME INITIALISING, YOU CAN ALSO USE THE "HELP" CHOICE HERE AS WELL AS IN EACH BLOCK OF THE MAIN PROGRAM TO KNOW MORE DETAILS ABOUT THE CODE')
        print('CAUTION: THERE IS A CHANCE OF AN UNEXPECTED UNBOUND ERROR ON OVER USE OF "BACK" FUNCTIONS WHILE EXITING THE PROGRAM, DO NOT PANIC!!!')
        print('')
        setup()
    elif(ch==2):
        print('Setting up may take a while...')
        mycursor.execute("DROP DATABASE IF EXISTS Library") 
        mycursor.execute("CREATE DATABASE Library")
        mycursor.execute("USE Library")
        mycursor.execute("CREATE TABLE books(Book_ID int(10) primary key,Book_Name varchar(30),Status varchar(20) DEFAULT'Available')")
        mycursor.execute("CREATE TABLE staff_fired(Staff_ID int(10) primary key,Staff_Name varchar(30),Age int(4),Mobile_Number varchar(30) unique key,Reason varchar(120))")
        mycursor.execute('CREATE TABLE staffs(Staff_ID int(10) primary key,Staff_Name varchar(30),Age int(4),Mobile_Number varchar(12) unique key,Password varchar(100),Warning int(10) default 0,Status varchar(30) default "Working")')
        mycursor.execute("CREATE TABLE stud_book(Student_ID_Number int(10),Student_Name varchar(30),Book_ID int(10) unique key,Book_Name varchar(30),Taken_Date varchar(100))")
        mycursor.execute("CREATE TABLE stud_profile(ID_Number int(10) primary key,Name varchar(30),Profile varchar(30))")
        mycursor.execute("CREATE TABLE students(ID_Number int(10) primary key,Name varchar(30),Class varchar(20),Mobile_Num varchar(22) unique key,Password varchar(100),Warning int(10) default 0,Profile varchar(30) default 'Active',Shout_out int(10) default 0,Membership varchar(30) default 'Temporary',Books_Taken int(10) default 0)")
        mycursor.execute("CREATE TABLE supervisor(SP_ID int(10) primary key,Name varchar(30),Password varchar(100))")
        print('')
        n=int(input('Enter no. of SuperVisors to manage your library:'))
        for i in range(n):
            a=int(input('Enter Supervisor ID:'))
            b=str(input('Enter Supervisor Name:'))
            c=str(input('Enter Password:'))
            sql='insert into supervisor(SP_ID,Name,Password) values(%s,%s,%s)'
            rol=[(a,b,c)]
            mycursor.executemany(sql, rol)
            print('')
        print('---YOUR PROGRAM HAS BEEN SUCCESSFULLY SETUP, NOW YOU CAN RUN YOUR PROGRAM---')
        print('')
        print("!!!CAUTION:DON'T RUN THIS PROGRAM UNLESS YOU WANT TO REBOOT YOUR LIBRARY(ERASE ALL DATA)!!!")
        con.commit()
        setup()
    elif(ch==3):
        print("HELP")
        print("----")
        print("Option (1) lets you see the basic things before using the program to get an idea about the program\nOption (2) is used for creating thr required tables for the program. This should be used only once!")
        setup()
    elif(ch==4):
        print("GOOD-BYE!")
        con.close()
setup()
